version: "3.9"

services:
  dao:
    build: .
    container_name: dao-test
    ports:
      - "3000:3000"
      - "8545:8545"
    # Only mount frontend if you want live reload
    volumes:
      - ./frontend:/app/frontend
    tty: true
